## --- App config ---
spring.application.name=League of stats

# --- Redis config ---
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=SECRET-KEY


# --- Telegram config ---
configuration.telegram-bot.username=league_of_stats_bot
configuration.telegram-bot.token=8129767304:AAF20f9WdDoIUnwEBohY9p5Iw8wudxLvSOE


## --- Riot config ---
configuration.riot-api.riot-api-token=RGAPI-8473dbb3-852d-4a83-a5ca-e1ac3a3642ef
configuration.riot-api.season-start-date-time=2024-01-10T00:00:00Z


## --- API urls ---
service.riot.base-url=https://{region}.api.riotgames.com
service.riot.accoutns.get-account.url=/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}
service.riot.league.get-entries.url=/lol/league/v4/entries/by-puuid/{encryptedPUUID}
service.riot.summoner.get-summoner-date.url=/lol/summoner/v4/summoners/by-puuid/{encryptedPUUID}
service.riot.match.get-match-ids-by-puuid.url=/lol/match/v5/matches/by-puuid/{puuid}/ids
service.riot.match.get-match-by-id.url=/lol/match/v5/matches/{matchId}