spring.application.name=League of stats


service.riot.api-key=SECRET-KEY
service.riot.base-url=https://{region}.api.riotgames.com

service.riot.accoutns.get-account.url=/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}
